### ISSUE TITLE
Add method for calculating mass of arbitrary IBHoMObject

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/ClimateEmergency_Toolkit#51]
#### Description:
Rather than getting CustomData.Volume, we can first check if there's sufficient location data defined in the object itself to calculate the volume, as well as the mass.

Add a method Mass() which takes an IBHoMObject and returns its mass, if it is defined or calculable.

**Comment by michaelhoehn** [comment]
Closing this issue as all EPD evaluation methods are now located within the LifeCycleAssessment_Toolkit. Additionally this issue has been resolved.
