### ISSUE TITLE
Re-factor EPD evaluation methods to one method which user can specify the quantity desired

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/ClimateEmergency_Toolkit#52]
#### Description:
Rather than separate, nearly identical methods for GlobalWarmingPotential, AcidificationPotential, etc., with each one using the same code to get the volume of the element, a single method could do all the work by having the user specify which quantity is required.

Create one method EvaluateEPD() which takes an object, an EPD, and the desired field from the EPD as a string and/or an enum.

**Comment by michaelhoehn** [comment]
closing this issue as all Evaluation methods for EPDs have transitioned to the LifeCycleAssessment_Toolkit and have been adjusted to reflect the issue raised here.
